### ISSUE TITLE
Simulations are opening in new tab and Some simulation sections are empty

### ISSUE THREAD

**Issue by madhavipuliraju** [vlabs-on-openedx/open-edx-virtual-anthropology-lab-iitg#1]
1) Simulations are opening in new tab 
2) Some simulation sections are empty

**Comment by mrudhvika940** [comment]
It is a downloadable simulation so it is redirecting to a new tab and also empty simulations were fixed

**Comment by sravanthimodepu** [comment]
Closing the issue.
