### ISSUE TITLE
'Analytics Usage' is not submitted because of special characters like '&' and 'comma'  in exp_name

### ISSUE THREAD

**Issue by madhavipuliraju** [vlabs-on-openedx/open-edx-virtual-anthropology-lab-iitg#3]
'Analytics Usage' is not submitted because of special characters like '&' and 'comma' in exp_name

**Comment by mrudhvika940** [comment]
Removed extra <script> tag from the code. Analytics usage is updating.

**Comment by sravanthimodepu** [comment]
Closing the issue, as the analytics usage is increasing.
